services:
  testssl-crond:
    image: testssl-crond
    container_name: testssl
    restart: always
    environment:
      # ip address or fqdn of the email server and port to send (no authorization support)
      - EMAIL_SERVER=1.2.3.4:25
      # email rewrite domain on who the email is from
      - EMAIL_DOMAIN=youremaildomain.com
      - TZ=America/Chicago
    volumes:
      # I have example files in the repo for email.txt domains.txt emailaddres.txt and mycron
      - /configs/testssl.sh/email.txt:/data/email.txt:ro
      - /configs/testssl.sh/domains.txt:/data/domains.txt:ro
      - /configs/testssl.sh/emailaddress.txt:/data/emailaddress.txt
      - /configs/testssl.sh/mycron:/etc/cron.d/mycron
